/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseDropdown: typeof import('./components/base/BaseDropdown.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseShimmer: typeof import('./components/base/BaseShimmer.vue')['default']
    BaseSteps: typeof import('./components/base/BaseSteps.vue')['default']
    HomeForm: typeof import('./components/home/HomeForm.vue')['default']
    HomeMarketing: typeof import('./components/home/HomeMarketing.vue')['default']
    IconChevronDown: typeof import('./components/icon/IconChevronDown.vue')['default']
    IconFlagCol: typeof import('./components/icon/IconFlagCol.vue')['default']
    IconFlagPh: typeof import('./components/icon/IconFlagPh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShimmerInput: typeof import('./components/ShimmerInput.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
